{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "paynexus.fullname" . }}-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "paynexus.fullname" . }}-rolebinding
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: {{ include "paynexus.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
