apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paynexus-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: paynexus.example
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: paynexus
                port:
                  number: 80
