apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: paynexus-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch", "create", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: paynexus-rolebinding
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: paynexus-role
  apiGroup: rbac.authorization.k8s.io
